name: Publish Pull Request
on: 
  push:
    branches:
      - develop
      - 'feature/**'
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
          contents : read
          pull-requests: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with: 
              node-version: 20
          - name: Setup Expo
            uses: expo/expo-github-action@v8
            with:
              expo-cache: true
              eas-version: latest
              token: ${{ secrets.EXPO_TOKEN }}
          - name: 📦 Install dependencies
            run: npm install
          - name: 📦 Publish to Expo Go
            run: NODE_ENV=dev expo publish --non-interactive --release-channel pr-${{ github.event.number }}
          - name: Add Expo link to PR
            uses: mshick/add-pr-comment@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              message: |
                ## Test this PR with Expo Go
                ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=exp://exp.host/@hemant08/quizapp?release-channel=pr-${{ github.event.number }})
                **------ Build published to [Expo](https://exp.host/@hemant08/quizapp?release-channel=pr-${{ github.event.number }}) ------**