name: Publish Pull Request
on: 
  push:
    branches:
      - develop
      - 'feature/**'
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
          contents : read
          pull-requests: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with: 
              node-version: 20
          - name: Setup Expo
            uses: expo/expo-github-action@v8
            with:
              eas-version: latest
              token: ${{ secrets.EXPO_TOKEN }}
          - name: 📦 Install dependencies
            run: npm install
          - name: 📦 Publish to Expo Go
            run: eas build --non-interactive --platform=production
          - name: Add Expo link to PR
            uses: mshick/add-pr-comment@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
              message: |
                **Hello**
                🌏
                !